import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Navbar from './components/Navbar'
import Footer from './components/Footer'
const inter = Inter({ subsets: ['latin'] })
import handleButtonClick from './components/Navbar'
export const metadata: Metadata = {
  title: 'Sujan Chaudhary Blog',
  description: 'Generated by Sujan Chaudhary',
}
export default function RootLayout({
  children,
}: {
  children: React.ReactNode,
}) {
  return (
    <html lang='en'>
      <body className={inter.className} onClick={handleButtonClick}>
          <Navbar />
          {children}
          <Footer />
      </body>
    </html >
  )
}